---
- name: Update apt package cache
  tags: util
  become: true
  when: ansible_os_family == 'Debian'
  apt:
    update_cache=yes
    cache_valid_time={{ util_apt_cache_valid_time }}


- name: Install Ansible SELinux dependencies
  tags: util
  become: true
  with_items: util_package_list_selinux
  action: "{{ ansible_pkg_mgr }} state={{ util_package_state }} name={{ item }}"
